### ISSUE TITLE
Develop using Coder and a remote container

### ISSUE THREAD

**Issue by eldad87** [ElliotG/coder-oss-tf#8]
Hi,
I would like to use Coder for cloud development in a microservices-orianted environment.
Is it possible to run the server on a separate pod than the actual dev pod?

**Comment by ElliotG** [comment]
I believe that each workspace is launched as it's own pod, so this should already be the case. Let me know if I'm wrong.

**Comment by eldad87** [comment]
Can you please share relevant documentation?
For example, how do I connect coder with a remote container?
