### ISSUE TITLE
Decentralized opensource cloud

### ISSUE THREAD

**Issue by weynandkuijpers** [ElliotG/coder-oss-tf#9]
Read about you vision that laptop (desktop, showing my age here) development is dead and that server based if the way forward.  Could not agree more, a laptop these days is "just a portable device that runs a browser".  So is a phone, tablet, anything basically. 

I am part of a group of people that has built an alternative to standard centralized clouds.  Have a look at [threefold.io](https://threefold.io/) and more specifically https://library.threefold.me/info/manual/#/manual3_iac/grid3_terraform/manual__grid3_terraform_home.

Let me know is this is something you like, we would like for you to include the coder-oss on the ThreeFold grid!

**Comment by ElliotG** [comment]
Sure, why not. I read through the docs that you linked, but the docs don't include the outputs that I would need to add this as an option. Something equivalent to this:

`provider "kubernetes" {
  host                   = digitalocean_kubernetes_cluster.coder.endpoint
  token                  = digitalocean_kubernetes_cluster.coder.kube_config[0].token
  cluster_ca_certificate = base64decode(digitalocean_kubernetes_cluster.coder.kube_config[0].cluster_ca_certificate)
}`

If you expanded your docs to include how to do both a kubernetes and helm integration, that would work. I also couldn't see clear instructions on if the grid_kubernetes supports add-ons like the CNI and CSI plugins

**Comment by ElliotG** [comment]
Closing this out for now. Feel free to reopen when you have the docs.
